
export const SET_PLAYING = 'SET_PLAYING';

export const SET_PLAYER_SHOW = 'SET_PLAYER_SHOW';

export const SET_SEARCHING = 'SET_SEARCHING';

export const SET_SEARCHING_FOCUS = 'SET_SEARCHING_FOCUS';

export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';

export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
