
export const SET_PLAYING = 'SET_PLAYING';

export const SET_SEARCHING = 'SET_SEARCHING';

export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS';

export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';
